# docker-compose.yml (đặt ở gốc repo)
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]   # tiện debug; có thể bỏ nếu muốn
    volumes:
      - mongodata:/data/db

  api:
    build: ./backend
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/food_delivery_db
      JWT_SECRET: dev-secret
      STRIPE_SECRET_KEY: dev-secret
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api

  admin:
    build:
      context: ./admin
      args:
        VITE_API_URL: http://localhost:5000
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - api

volumes:
  mongodata: