name: Docker build & push (GHCR)

on:
push:
branches: [main]
workflow_dispatch:

permissions:
contents: read
packages: write

jobs:
build:
runs-on: ubuntu-latest

text

strategy:
  matrix:
    include:
      - name: api
        context: ./backend
        file: ./backend/Dockerfile
      - name: web
        context: ./frontend
        file: ./frontend/Dockerfile
        build_args: VITE_API_URL=http://localhost:5000
      - name: admin
        context: ./admin
        file: ./admin/Dockerfile
        build_args: VITE_API_URL=http://localhost:5000

steps:
  - uses: actions/checkout@v4

  - name: Set lowercase repo
    run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

  - uses: docker/setup-buildx-action@v3

  - name: Login GHCR
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Build & push images
    uses: docker/build-push-action@v6
    with:
      push: true
      platforms: linux/amd64
      context: ${{ matrix.context }}
      file: ${{ matrix.file }}
      tags: |
        ghcr.io/${{ env.REPO_LC }}:${{ matrix.name }}-latest
        ghcr.io/${{ env.REPO_LC }}:${{ matrix.name }}-${{ github.sha }}
      # nếu entry không có build_args thì tham số này sẽ trống (không sao)
      build-args: ${{ matrix.build_args }}
      cache-from: type=gha
      cache-to: type=gha,mode=max